#!/usr/bin/env ruby

require 'erb'
require 'json'

@months = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" ]

#========================================================================
# Methods used within templates
#------------------------------------------------------------------------
def render(path, **hash_params)
  full_path = File.join(__dir__, ".scaffolds", path)
  ERB.new(File.read(full_path)).result(binding)
end

def stat_box(turn, box)
  "<span class=\"box\">#{box =~ /\d+/ && box.to_i <= turn ? box : '&nbsp;'}</span>"
end

#========================================================================
# Main program
#------------------------------------------------------------------------

print "Date of Battle (YYYYMMDD)? "
@date_str = gets.chomp

@month = @date_str[4,2].sub /^0/, ""

@friendly_date_str = "#{@date_str[6,8]} #{@months[@month.to_i]} #{@date_str[0,4]}"

Dir.mkdir("LotR-#{@date_str}", 0755) unless Dir.exist?("LotR-#{@date_str}")
Dir.mkdir("LotR-#{@date_str}/Thumbnails", 0755) unless Dir.exist?("LotR-#{@date_str}/Thumbnails")
Dir.mkdir("LotR-#{@date_str}/Images", 0755) unless Dir.exist?("LotR-#{@date_str}/Images")

stats_file_name = "LotR-#{@date_str}/hero-stats.json"
@hero_stats = File.exist?(stats_file_name) ? JSON.parse(File.read(stats_file_name)) : nil

print "Scenario Name? "
@scenario_name = gets.chomp

print "Number of Turns? "
@num_turns = gets.chomp.to_i

@index = render("lotr-template.erb", num_turns: @num_turns, friendly_date: @friendly_date_str)

File.write("LotR-#{@date_str}/index.html", @index, :encoding => "UTF-8")
