#!/usr/bin/env ruby

require 'oga'

abort "usage: update-indexes" unless ARGV.size == 0

print "Directory Name? "
@dir_name = gets.chomp

@dir_name.chop if @dir_name =~ %r{/$}

print "Thumbnail image name (e.g. IMG_1229.JPG)? "
@img_name = gets.chomp

fh = File.open("#{@dir_name}/index.html")
@doc = Oga.parse_html(fh)
@title = @doc.xpath("/html/body/h1/text()").text

@date = "#{@dir_name[5..8]}-#{@dir_name[9..10]}-#{@dir_name[11..12]}"

File.open("_lotr.html", "w") do |out|
  File.open("lotr.html").each_line do |line|

    out.puts line
    if line =~ /<!-- NEXT -->/
      out.puts <<~BLOCK

        <div class="reportToc">
          <div class="thumbnail"><a href="#{@dir_name}/"><img src="#{@dir_name}/Thumbnails/th#{@img_name}"></a></div>
          <div class="titleLink"><a href="#{@dir_name}/">#{@title}</a></div>
          <div class="date">#{@date}</div>
        </div>
      BLOCK
    end
  end
end

File.rename "_lotr.html", "lotr.html"
puts "Updated lotr.html"

File.open("_lotr.html", "w") do |out|
  File.open("lotr-amp.html").each_line do |line|

    out.puts line
    if line =~ /<!-- NEXT -->/
      out.puts <<~BLOCK

          <div class="reportToc">
            <div class="thumbnail"><a href="#{@dir_name}/"><img src="#{@dir_name}/Thumbnails/th#{@img_name}"></a></div>
            <div class="titleLink"><a href="#{@dir_name}/">#{@title}</a></div>
            <div class="date">#{@date}</div>
          </div>
      BLOCK
    end
  end
end

File.rename "_lotr.html", "lotr-amp.html"
puts "Updated lotr-amp.html"
